### ISSUE TITLE
Drop support for node.js <=6

### ISSUE THREAD

**Issue by StringEpsilon** [SimenB/realpath-native#48]
As node 6 is out of support for over a year now, dropping it should not cause any issues.

Would also allow dropping the dependency `util.promisify`, as the API is provided by NodeJs 8.0.0 and higher.

And it would result in 1.18mb drop in install size: https://packagephobia.now.sh/result?p=util.promisify

**Comment by SimenB** [comment]
Yeah, let's do it! Wanna send a PR?

(let's keep node 8 support so we can upgrade jest)

**Comment by StringEpsilon** [comment]
I'll get back to you later this evening.

**Comment by SimenB** [comment]
Note that this module is just needed for node 8 which is EOL. So if you just support the currently supported versions of node this module is unneeded. I'll be deprecating it as soon as Jest no longer needs it (Jest v26)
